In [20]:
import pandas as pd

In [21]:
import numpy as np

import matplotlib.pyplot as plt

In [22]:
df = pd.DataFrame({
    'Maths':[89,20,45,43,56,77,np.nan,43,21,12,np.nan],
    'English':[2,22,12,43,56,27,np.nan,np.nan,21,np.nan,np.nan]
})
df

    Maths  English
0    89.0      2.0
1    20.0     22.0
2    45.0     12.0
3    43.0     43.0
4    56.0     56.0
5    77.0     27.0
6     NaN      NaN
7    43.0      NaN
8    21.0     21.0
9    12.0      NaN
10    NaN      NaN

In [23]:
df.fillna(df.mean() , inplace = True)

In [25]:
df

        Maths    English
0   89.000000   2.000000
1   20.000000  22.000000
2   45.000000  12.000000
3   43.000000  43.000000
4   56.000000  56.000000
5   77.000000  27.000000
6   45.111111  26.142857
7   43.000000  26.142857
8   21.000000  21.000000
9   12.000000  26.142857
10  45.111111  26.142857